name: wtw_app
description: 'A new travel pal for you and your friends.'

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  animate_do: ^3.1.2
  cloud_firestore: ^4.13.1
  cupertino_icons: ^1.0.2
  either_dart: ^1.0.0
  envied: ^0.5.2
  firebase_auth: ^4.14.0
  firebase_core: ^2.22.0
  firebase_storage: ^11.5.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.6
  freezed_annotation: ^2.4.1
  go_router: ^12.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.1
  intl_utils: ^2.8.5
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  phosphor_flutter: ^2.0.1
  translator: ^0.1.7

dev_dependencies:
  build_runner: ^2.4.6
  envied_generator: ^0.5.2
  flutter_gen_runner: ^5.3.2
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.5
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1
  mocktail: ^1.0.1

flutter:
  uses-material-design: true
  generate: true

flutter_intl:
  enabled: true
  class_name: S
  main_locale: es
  arb_dir: lib/l10n
  output_dir: lib/gen

flutter_gen:
  output: lib/gen
